[cmug]
user="root"
password="12345"
host="127.0.0.1"
port="3306"
db="cmug"
table="opencmug"

[runaway]
user="runaway"
password="run@2018"
host="127.0.0.1"
port="3306"
db="runaway"
table="cmug_summary"
