[ordercenter]
user="admin"
password="78q3letSPQGuAwDG1Meq6yO5O"
host="10.104.36.85"
port="15004"
db="ordercenter"
table="order_info"

[runaway]
user="runaway"
password="run@2018"
host="10.104.132.62"
port="3306"
db="runaway"
table="order_summary"
